### ISSUE TITLE
When splitting data, how do you make sure that there is no zero value assigned to nn.nan?

### ISSUE THREAD

**Issue by MartinBagaram** [MartinBagaram/matrix_completion#1]
When converting the data I realized that you converted it to the log scale and then later you created the matrix by transforming the data from its long-skinny format to a matrix like format. You introduced np.nan by replacing zeros by nan. How do you make sure that some of the zeros are not just due to log(1)?

I don't know if I make sense

**Comment by qcao10** [comment]
Yes, that totally makes sense. We can do a quick check if any entries == 1.0. If there are some, we can just add an epsilon = 0.001 to everything and take log. It won't cause much problem for such a small adjustment, I think.
